
server.port=${PORT:8082}

spring.application.name=Micro-Project-Order-Service

#RabbitMQ configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST}
RABBITMQ_QUEUE=${QUEUE_NAME}
spring.rabbitmq.ssl.enabled=true

spring.main.allow-bean-definition-overriding=true
#
product-service.base-url=http://localhost:8081

AUTH_SERVICE_BASE_URL=${AUTH_SERVICE_BASE_URL}