
server.port=${PORT:8082}

spring.application.name=Micro-Project-Order-Service
spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=${AMQP_USERNAME}
spring.rabbitmq.password=${AMQP_PASSWORD}
spring.rabbitmq.virtual-host=${AMQP_USERNAME}
spring.rabbitmq.ssl.enabled=true

RABBITMQ_QUEUE=confirmation-queue

product-service.port-url=${PRODUCT_SERVICE_URL:http://localhost:8081}