
server.port=${PORT:8082}

spring.application.name=Micro-Project-Order-Service

#RabbitMQ configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VHOST}
RABBITMQ_QUEUE=${QUEUE_NAME:orderEmailQueue}
spring.rabbitmq.ssl.enabled=true

spring.main.allow-bean-definition-overriding=true

product-service_base-url=${PRODUCT_SERVICE_BASE_URL}

AUTH_SERVICE_BASE_URL=${AUTH_SERVICE_BASE_URL}


spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

debug=true



server.forward-headers-strategy=framework